import java.awt.Color;
import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
public class register extends javax.swing.JFrame {

    public register() {
        initComponents();
        Border borderLabel=BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        lblclose.setBorder(borderLabel);
        lblminimize.setBorder(borderLabel);
        Border borderTextField=BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        txtiduser.setBorder(borderTextField);
        txtnomuser.setBorder(borderTextField); 
        txtprenomuser.setBorder(borderTextField);
        txtusername.setBorder(borderTextField);
        txtpassuser.setBorder(borderTextField);
        txtconfirmuser.setBorder(borderTextField);
        txtteluser.setBorder(borderTextField);
        txtadressuser.setBorder(borderTextField);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblclose = new javax.swing.JLabel();
        lblminimize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtteluser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtadressuser = new javax.swing.JTextField();
        txtpassuser = new javax.swing.JPasswordField();
        txtconfirmuser = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnretourner = new javax.swing.JButton();
        txtnomuser = new javax.swing.JTextField();
        txtprenomuser = new javax.swing.JTextField();
        txtiduser = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        rbfemme = new javax.swing.JRadioButton();
        btnretourner1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(640, 427));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 427));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblclose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblclose.setText("X");
        lblclose.setPreferredSize(new java.awt.Dimension(17, 17));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 23, -1));

        lblminimize.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblminimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminimize.setText("-");
        lblminimize.setPreferredSize(new java.awt.Dimension(17, 17));
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
        });
        getContentPane().add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,140));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtteluser.setBackground(new java.awt.Color(204, 204, 255));
        txtteluser.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtteluser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtteluser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteluserActionPerformed(evt);
            }
        });
        txtteluser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtteluserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteluserKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TELEPHONE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CIN:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOM:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ADRESSE:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PRENOM:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("GENRE:");

        txtadressuser.setBackground(new java.awt.Color(204, 204, 255));
        txtadressuser.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtadressuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtadressuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadressuserActionPerformed(evt);
            }
        });

        txtpassuser.setBackground(new java.awt.Color(204, 204, 255));
        txtpassuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtpassuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtconfirmuser.setBackground(new java.awt.Color(204, 204, 255));
        txtconfirmuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtconfirmuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtconfirmuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmuserActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CONFIRMER: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("MOT DE PASSE:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOM D'UTILISATEUR:");

        btnretourner.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnretourner.setForeground(new java.awt.Color(0, 51, 102));
        btnretourner.setText("RETOURNER");
        btnretourner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnretourner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnretournerMouseClicked(evt);
            }
        });
        btnretourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretournerActionPerformed(evt);
            }
        });

        txtnomuser.setBackground(new java.awt.Color(204, 204, 255));
        txtnomuser.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtnomuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtprenomuser.setBackground(new java.awt.Color(204, 204, 255));
        txtprenomuser.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtprenomuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtiduser.setBackground(new java.awt.Color(204, 204, 255));
        txtiduser.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtiduser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtusername.setBackground(new java.awt.Color(204, 204, 255));
        txtusername.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Homme");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(rbfemme);
        rbfemme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbfemme.setForeground(new java.awt.Color(0, 102, 102));
        rbfemme.setText("Femme");
        rbfemme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbfemme)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(rbfemme))
                .addContainerGap())
        );

        btnretourner1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnretourner1.setForeground(new java.awt.Color(204, 0, 0));
        btnretourner1.setText("ENREGISTRER");
        btnretourner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnretourner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnretourner1MouseClicked(evt);
            }
        });
        btnretourner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourner1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnomuser)
                                            .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtadressuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtprenomuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtconfirmuser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(4, 4, 4)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtteluser)
                                            .addComponent(txtpassuser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnretourner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnretourner1)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtteluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpassuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnomuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprenomuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtadressuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(txtconfirmuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnretourner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnretourner1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 570, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photos/back1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean checkEmptyField(){
        return(txtiduser.getText().equals("")||txtnomuser.getText().equals("")||txtprenomuser.getText().equals("")||String.valueOf(txtconfirmuser.getPassword()).equals("")||txtteluser.getText().equals("")||txtadressuser.getText().equals("")||txtusername.getText().equals("")||String.valueOf(txtpassuser.getPassword()).equals("")/*||lblimagepath.getText().equals("image path")*/);
    }
    private boolean matchingpasswords(String p1,String p2){
        return(p1.equals(p2));
    }
    private boolean checkuser(){
        PreparedStatement ps;
        ResultSet rs;
        boolean userexist=false;
        String query="SELECT username FROM reservation_chambres_hotel.user WHERE type='client' and username=?";
        try{
            ps=ConnectionDB.getConnection().prepareStatement(query);
            
            ps.setString(1, txtusername.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                userexist=true;
                JOptionPane.showMessageDialog(null,"Compte exist déja !", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Pas de connection avec la base de donnees !"+ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
        return userexist;
    }
    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void txtadressuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadressuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadressuserActionPerformed

    private void txtconfirmuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmuserActionPerformed

    private void txtteluserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteluserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteluserActionPerformed

    private void btnretournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretournerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretournerActionPerformed

    private void btnretournerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretournerMouseClicked
        login login=new login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnretournerMouseClicked

        
        
    private void txtteluserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteluserKeyTyped
        char key=evt.getKeyChar();
        if(!Character.isDigit(key))
            evt.consume();//maynajem ydakhel ken ar9am
    }//GEN-LAST:event_txtteluserKeyTyped

    private void txtteluserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteluserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteluserKeyPressed

    private void btnretourner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourner1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretourner1MouseClicked

    private void btnretourner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourner1ActionPerformed
        if (checkEmptyField()){
            JOptionPane.showMessageDialog(null,"if faut entrer tous les données", "Missing data", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String id =txtiduser.getText();
            String nom=txtnomuser.getText();
            String prenom=txtprenomuser.getText();
            String username=txtusername.getText();
            String tel=txtteluser.getText();
            String adress=txtadressuser.getText();
            String password=String.valueOf(txtpassuser.getPassword());
            String confirmpassword=String.valueOf(txtconfirmuser.getPassword());
            String type="client";
            String genre="homme";
            if(rbfemme.isSelected())
            genre="femme";
            if (!matchingpasswords(password,confirmpassword)){
                JOptionPane.showMessageDialog(null,"Mots de passe incompatibles", "Passwords!", JOptionPane.ERROR_MESSAGE);}
            else{
                PreparedStatement ps;
                String query="INSERT INTO reservation_chambres_hotel.user(cin,nom,prenom,tel,adresse,username,password,genre,type) values(?,?,?,?,?,?,?,?,?) ";
                try{
                    ps=ConnectionDB.getConnection().prepareStatement(query);
                    ps.setString(1,id);
                    ps.setString(2,nom);
                    ps.setString(3,prenom);
                    ps.setString(4,tel);
                    ps.setString(5,adress);
                    ps.setString(6,username);
                    ps.setString(7,password);
                    ps.setString(8,genre);
                    ps.setString(9,type);
                    if(!checkuser()){
                        if(ps.executeUpdate()!=0){
                            JOptionPane.showMessageDialog(null,"Compte crée", "Success !", JOptionPane.PLAIN_MESSAGE);
                        }
                    }
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Pas de connection avec la base de donnees !"+ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnretourner1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               register register= new register();
               register.setVisible(true);
               register.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnretourner;
    private javax.swing.JButton btnretourner1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JRadioButton rbfemme;
    private javax.swing.JTextField txtadressuser;
    private javax.swing.JPasswordField txtconfirmuser;
    private javax.swing.JTextField txtiduser;
    private javax.swing.JTextField txtnomuser;
    private javax.swing.JPasswordField txtpassuser;
    private javax.swing.JTextField txtprenomuser;
    private javax.swing.JTextField txtteluser;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private void getKeyChar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
